/*
    Always Encrypted schema template.

    Replace:
    - $(KeyVaultKeyUrl) with the versioned Key Vault key URL from the Bicep output.
    - $(CekEncryptedValue) with the encrypted CEK value generated by SSMS or the SqlServer PowerShell module.

    The SQL Admin should not receive permissions to unwrap/decrypt the Key Vault key.
*/

CREATE COLUMN MASTER KEY [CMK_Documents_Akv]
WITH
(
    KEY_STORE_PROVIDER_NAME = N'AZURE_KEY_VAULT',
    KEY_PATH = N'$(KeyVaultKeyUrl)'
);
GO

CREATE COLUMN ENCRYPTION KEY [CEK_Documents]
WITH VALUES
(
    COLUMN_MASTER_KEY = [CMK_Documents_Akv],
    ALGORITHM = 'RSA_OAEP',
    ENCRYPTED_VALUE = 0x$(CekEncryptedValue)
);
GO

CREATE TABLE dbo.Documents
(
    DocumentId uniqueidentifier NOT NULL
        CONSTRAINT PK_Documents PRIMARY KEY,
    SenderTenantId uniqueidentifier NOT NULL,
    SenderObjectId uniqueidentifier NOT NULL,
    ReceiverTenantId uniqueidentifier NOT NULL,
    ReceiverObjectId uniqueidentifier NOT NULL,
    FileName nvarchar(256) NOT NULL,
    ContentType nvarchar(128) NOT NULL,
    EncryptedPayload varbinary(max) ENCRYPTED WITH
    (
        COLUMN_ENCRYPTION_KEY = [CEK_Documents],
        ENCRYPTION_TYPE = Randomized,
        ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
    ) NOT NULL,
    CreatedAt datetime2(7) NOT NULL
        CONSTRAINT DF_Documents_CreatedAt DEFAULT SYSUTCDATETIME(),
    ReadAt datetime2(7) NULL
);
GO

CREATE INDEX IX_Documents_Receiver
ON dbo.Documents (ReceiverTenantId, ReceiverObjectId, CreatedAt);
GO

CREATE TABLE dbo.DocumentAccessAudit
(
    AuditId bigint IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_DocumentAccessAudit PRIMARY KEY,
    DocumentId uniqueidentifier NULL,
    Action nvarchar(64) NOT NULL,
    TenantId uniqueidentifier NOT NULL,
    ObjectId uniqueidentifier NOT NULL,
    Result nvarchar(32) NOT NULL,
    CorrelationId uniqueidentifier NOT NULL,
    CreatedAt datetime2(7) NOT NULL
        CONSTRAINT DF_DocumentAccessAudit_CreatedAt DEFAULT SYSUTCDATETIME()
);
GO

CREATE INDEX IX_DocumentAccessAudit_DocumentId
ON dbo.DocumentAccessAudit (DocumentId, CreatedAt);
GO

